MountainHotels/Models/ErrorViewModel.cs
namespace MountainHotels.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MountainHotels/Models/Hotel.cs
namespace MountainHotels.Models
{
    public class Hotel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}

MountainHotels/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MountainHotels.Models;
using System.Diagnostics;

namespace MountainHotels.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MountainHotels/Controllers/HotelsController.cs
using Microsoft.AspNetCore.Mvc;
using MountainHotels.DataAccess;
using MountainHotels.Models;

namespace MountainHotels.Controllers
{
    public class HotelsController : Controller
    {
        private readonly MountainHotelsContext _context;

        public HotelsController(MountainHotelsContext context)
        {
            _context = context;
        }

        // GET: /Hotels
        public IActionResult Index(string? location)
        {
            var hotels = _context.Hotels.AsEnumerable();
            if(location != null)
            {
                hotels = hotels.Where(h => h.Location == location);
                ViewData["Location"] = location;
            }
            
            ViewData["allLocations"] = _context.Hotels.Select(h => h.Location).Distinct().ToList();

            return View(hotels);
        }

        // GET: /Hotels/New
        public IActionResult New()
        {
            return View();
        }

        // POST: /Hotels
        [HttpPost]
        public IActionResult Index(Hotel hotel)
        {
            //Take the movie sent in the request and save it to the database
            _context.Hotels.Add(hotel);
            _context.SaveChanges();

            // Redirect back to the index page with all hotels
            return RedirectToAction("Index");
        }
    }
}

MountainHotels/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MountainHotels/Views/Hotels/Index.cshtml
@model IEnumerable<Hotel>
@{
    List<string> allLocations = ViewData["allLocations"] as List<string>;
}
<h1>Summit Slope Retreats</h1>

<h3>Location Filter</h3>
@if (ViewData["Location"] != null)
{
    <p>Filtering by: <strong>@ViewData["Location"]</strong></p>
}
<ul>
    <li><a href="/hotels">All</a></li>
    @foreach(var location in allLocations)
    {
        <li><a href="/hotels?location=@location">@location</a></li>
    }
</ul>

<h3>All Hotels</h3>

<ul>
@foreach (var hotel in Model)
{
    <li>
        <strong>Name:</strong> @hotel.Name, <strong>Location:</strong> @hotel.Location
    </li>
}
</ul>

MountainHotels/Views/Hotels/New.cshtml
<h1>Add a Hotel</h1>

<form method="post" action="/hotels">
    <div class="form-group">
        <label for="Name">Name:</label>
        <input type="text" id="Name" name="Name"/>
    </div>
    <div class="form-group">
        <label for="Location">Location:</label>
        <input type="text" id="Location" name="Location" />
    </div>
    <button type="submit">Add Hotel</button>
</form>

MountainHotels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MountainHotels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MountainHotels.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MountainHotels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotels" asp-action="Index">Hotels</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MountainHotels - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>